server:
  port: ${PORT:8866}

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@hippo-cluster-gya0k.mongodb.net/hippo-survey-db?retryWrites=true

service:
  user-analytics:
    host: ${ANALYTICS_HOST:localhost}
    port: ${ANALYTICS_PORT:8855}

auth0:
  issuer: https://hippo-survey.eu.auth0.com/
  apiAudience: https://hippo-survey-core.herokuapp.com/

analytics:
  train-threshold: 2
  retrain-factor: 1