server:
  port: ${PORT:8866}
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${DOMAIN_NAME:localhost}
    non-secure-port: 80

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA:http://localhost:8761}/eureka
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@hippo-cluster-gya0k.mongodb.net/hippo-survey-db?retryWrites=true

service:
  user-analytics:
    serviceId: HIPPO-USER-ANALYTICS

auth0:
  issuer: https://hippo-survey.eu.auth0.com/
  apiAudience: http://localhost:${server.port}

analytics:
  train-threshold: 2
  retrain-factor: 1