server:
  port: 8866
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@hippo-cluster-gya0k.mongodb.net/hippo-survey-db?retryWrites=true

service:
  user-analytics:
    serviceId: HIPPO-USER-ANALYTICS

auth0:
  issuer: https://hippo-survey.eu.auth0.com/
  apiAudience: http://localhost:8866

analytics:
  train-threshold: 15
  retrain-factor: 5